on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  checks: write
  pages: write
env:
  RUST_BACKTRACE: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  DeterminateCI:
    uses: conneroisu/ci/.github/workflows/workflow.yml@main
    with:
      visibility: public
      fail-fast: true
  build-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - DeterminateCI
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run build
        run: cd doc/ && nix build -L --accept-flake-config '.#'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./doc/result
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: build-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      - name: Link to the GitHub Pages
        run: |
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
          echo "View the documentation at ${{ steps.deployment.outputs.page_url }}"
